# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - Matcher$
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - depguard
    - dupword
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - ireturn
    - lll
    - mnd
    - nonamedreturns
    - nolintlint # https://github.com/golangci/golangci-lint/issues/3063
    - paralleltest
    - tagliatelle
    - tenv
    - testpackage
    - varnamelen
    - wrapcheck

issues:
  max-same-issues: 20
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - err113
        - funlen
        - goconst
        - mnd
        - noctx
      path: "_test.go"
