structname: "{{.InterfaceName}}"
filename: "{{ .InterfaceName | snakecase }}.go"
dir: "{{.InterfaceDir}}/mock"
pkgname: mock
packages:
  go.nhat.io/matcher/v3:
    config:
      dir: "mock"
      include-interface-regex: "Matcher"
      pkgname: mock
